---
apiVersion: v1
kind: ConfigMap
metadata:
  name: joke-gateway-config
  namespace: joke-platform
data:
  JOKE_GENERATOR_URL: "http://prod-joke-generator:8081"
  PUNCHLINE_SERVICE_URL: "http://prod-punchline-service:8082"
  AUDIENCE_SERVICE_URL: "http://prod-audience-service:8083"
  CHAOS_COMEDIAN_URL: "http://prod-chaos-comedian:8084"
