INSERT INTO joke_setups (id, category, text, created_at) VALUES
    ('programming-001', 'programming', 'Why did the developer go broke?', CURRENT_TIMESTAMP),
    ('programming-002', 'programming', 'Why do Java developers wear glasses?', CURRENT_TIMESTAMP),
    ('programming-003', 'programming', 'How many programmers does it take to change a light bulb?', CURRENT_TIMESTAMP),
    ('programming-004', 'programming', 'Why did the function stop calling its arguments?', CURRENT_TIMESTAMP),
    ('kubernetes-001', 'kubernetes', 'Why did the Kubernetes pod visit a therapist?', CURRENT_TIMESTAMP),
    ('kubernetes-002', 'kubernetes', 'Why did the container refuse to leave the cluster?', CURRENT_TIMESTAMP),
    ('kubernetes-003', 'kubernetes', 'Why was the Kubernetes administrator so calm during the outage?', CURRENT_TIMESTAMP),
    ('kubernetes-004', 'kubernetes', 'What did one replica say to the other replica?', CURRENT_TIMESTAMP),
    ('dad-001', 'dad', 'Why could the bicycle not stand up by itself?', CURRENT_TIMESTAMP),
    ('dad-002', 'dad', 'What do you call cheese that does not belong to you?', CURRENT_TIMESTAMP),
    ('dad-003', 'dad', 'Why did the scarecrow win an award?', CURRENT_TIMESTAMP),
    ('dad-004', 'dad', 'Why do fathers take an extra pair of socks golfing?', CURRENT_TIMESTAMP),
    ('animal-001', 'animal', 'What do you call a bear with no teeth?', CURRENT_TIMESTAMP),
    ('animal-002', 'animal', 'Why do cows wear bells?', CURRENT_TIMESTAMP),
    ('animal-003', 'animal', 'What do you call an alligator wearing a vest?', CURRENT_TIMESTAMP),
    ('animal-004', 'animal', 'Why did the chicken join a Kubernetes cluster?', CURRENT_TIMESTAMP),
    ('science-001', 'science', 'Why can you never trust an atom?', CURRENT_TIMESTAMP),
    ('science-002', 'science', 'Why did the photon refuse to check a suitcase?', CURRENT_TIMESTAMP),
    ('science-003', 'science', 'What did the biologist wear to impress the other scientists?', CURRENT_TIMESTAMP),
    ('science-004', 'science', 'Why was the math book unhappy?', CURRENT_TIMESTAMP);
