---
apiVersion: v1
kind: ConfigMap
metadata:
  name: joke-generator-config
  namespace: joke-platform
data:
  DB_HOST: "local-joke-platform-db-rw"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: punchline-service-config
  namespace: joke-platform
data:
  DB_HOST: "local-joke-platform-db-rw"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: audience-service-config
  namespace: joke-platform
data:
  DB_HOST: "local-joke-platform-db-rw"
