apiVersion: apps/v1
kind: Deployment
metadata:
  name: joke-gateway
  namespace: joke-platform
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: joke-generator
  namespace: joke-platform
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: punchline-service
  namespace: joke-platform
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: audience-service
  namespace: joke-platform
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaos-comedian
  namespace: joke-platform
spec:
  replicas: 1
