apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: local-

bases:
  - ../../base

patchesStrategicMerge:
  - deployment-replicas.yaml
  - resource-limits.yaml
  - configmap-db-host.yaml
  - configmap-gateway-urls.yaml
  - cnpg-cluster.yaml

configMapGenerator:
  - name: environment-config
    literals:
      - ENVIRONMENT=local
      - LOG_LEVEL=DEBUG

images:
  - name: harbor.container.it-scholar.com/joke-platform/joke-gateway
    newTag: dev
  - name: harbor.container.it-scholar.com/joke-platform/joke-generator
    newTag: dev
  - name: harbor.container.it-scholar.com/joke-platform/punchline-service
    newTag: dev
  - name: harbor.container.it-scholar.com/joke-platform/audience-service
    newTag: dev
  - name: harbor.container.it-scholar.com/joke-platform/chaos-comedian
    newTag: dev
