apiVersion: v1
kind: ConfigMap
metadata:
  name: joke-gateway-config
  namespace: joke-platform
  labels:
    app.kubernetes.io/name: joke-gateway
    app.kubernetes.io/component: gateway
    app.kubernetes.io/part-of: joke-platform
data:
  SERVER_PORT: "8080"
  THYMELEAF_CACHE: "true"
  JOKE_GENERATOR_URL: "http://joke-generator:8081"
  PUNCHLINE_SERVICE_URL: "http://punchline-service:8082"
  AUDIENCE_SERVICE_URL: "http://audience-service:8083"
  CHAOS_COMEDIAN_URL: "http://chaos-comedian:8084"
  BACKEND_CONNECT_TIMEOUT_MS: "2000"
  BACKEND_READ_TIMEOUT_MS: "7000"
