---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: joke-platform
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: datastore
    app.kubernetes.io/part-of: joke-platform
data:
  POSTGRES_DB: "joke-platform"
  POSTGRES_USER: "jokes"
