apiVersion: v1
kind: ConfigMap
metadata:
  name: joke-generator-config
  namespace: joke-platform
  labels:
    app.kubernetes.io/name: joke-generator
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: joke-platform
data:
  SERVER_PORT: "8081"
  DB_HOST: "joke-platform-db-rw"
  DB_PORT: "5432"
  DB_NAME: "joke-platform"
  DB_USERNAME: "jokes"
  JOKE_GENERATOR_REPOSITORY_PROVIDER: "database"
