apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: joke-platform

resources:
  - namespace.yaml
  - secrets.yaml
  - cnpg-cluster.yaml
  - configmap-joke-gateway.yaml
  - configmap-joke-generator.yaml
  - configmap-punchline-service.yaml
  - configmap-audience-service.yaml
  - configmap-chaos-comedian.yaml
  - deployment-joke-gateway.yaml
  - deployment-joke-generator.yaml
  - deployment-punchline-service.yaml
  - deployment-audience-service.yaml
  - deployment-chaos-comedian.yaml
  - service-joke-gateway.yaml
  - service-joke-generator.yaml
  - service-punchline-service.yaml
  - service-audience-service.yaml
  - service-chaos-comedian.yaml
  - statefulset-redis.yaml
  - statefulset-rabbitmq.yaml
  - networkpolicy.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: joke-platform

images:
  - name: harbor.bcp.education/joke-platform/joke-gateway
    newName: harbor.container.it-scholar.com/joke-platform/joke-gateway
    newTag: local
  - name: harbor.bcp.education/joke-platform/joke-generator
    newName: harbor.container.it-scholar.com/joke-platform/joke-generator
    newTag: latest
  - name: harbor.bcp.education/joke-platform/punchline-service
    newName: harbor.container.it-scholar.com/joke-platform/punchline-service
    newTag: 1.0.0
  - name: harbor.bcp.education/joke-platform/audience-service
    newName: harbor.container.it-scholar.com/joke-platform/audience-service
    newTag: local
  - name: harbor.bcp.education/joke-platform/chaos-comedian
    newName: harbor.container.it-scholar.com/joke-platform/chaos-comedian
    newTag: 0.0.1
