---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: joke-platform
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/part-of: joke-platform
type: Opaque
stringData:
  username: jokes
  password: jokes-platform-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials
  namespace: joke-platform
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: joke-platform
type: Opaque
stringData:
  password: redis-platform-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: joke-platform
  labels:
    app.kubernetes.io/name: joke-platform-db
    app.kubernetes.io/part-of: joke-platform
type: Opaque
stringData:
  username: jokes
  password: jokes-platform-secret
