apiVersion: v1
kind: Service
metadata:
  name: chaos-comedian
  namespace: joke-platform
  labels:
    app.kubernetes.io/name: chaos-comedian
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: joke-platform
spec:
  type: ClusterIP
  ports:
  - port: 8084
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: chaos-comedian
    app.kubernetes.io/component: backend
